### ISSUE TITLE
Windows 10, P52 (Xeon + P2000 Nvidia)

### ISSUE THREAD

**Issue by lawrenceong001** [MauriceGit/Voronoi_Image_Manipulation#4]
hi, 

i'm able now to run get & build, which results in an executable file. however, when i run it, the screen blinks for a while, and it just quits with no messages. any advice on how to debug this? 

tks
lawrence

**Comment by lawrenceong001** [comment]
running in VSCode, it appears that when I debug it it fails with this message:

`Exception 0xc0000005 0x8 0x0 0x0`
`PC=0x0`
`signal arrived during external code execution`
``
`github.com/go-gl/gl/v4.1-core/gl._Cfunc_glowCreateShader(0x0, 0x8b31, 0x0)`
`	_cgo_gotypes.go:5440 +0x54`
`github.com/go-gl/gl/v4.1-core/gl.CreateShader(0x101430000008b31, 0x0)`
`	C:/Users/L/go/src/github.com/go-gl/gl/v4.1-core/gl/package.go:9076 +0x44`
`github.com/MauriceGit/mtOpenGL.compileShader(0xc0000c0000, 0x4a8, 0xc000008b31, 0x0, 0x0, 0x0)`
`	C:/Users/L/go/src/github.com/MauriceGit/mtOpenGL/mtOpenGL.go:24 +0x5e`
`github.com/MauriceGit/mtOpenGL.NewProgram(0xc0000ae000, 0x10, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc0000ae010, 0xd, ...)`
`	C:/Users/L/go/src/github.com/MauriceGit/mtOpenGL/mtOpenGL.go:70 +0x1ae`
`main.InitializeRender(0xc000014240, 0xc000048070, 0xc0, 0x78da04, 0x12)`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/glView.go:829 +0x2c3`
`main.main()`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:438 +0x155`
``
`goroutine 6 [chan receive]:`
`main.main.func1(0xc000048070)`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:432 +0x3b`
`created by main.main`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:431 +0xd0`

`goroutine 7 [chan send]:`
`main.setDefaultRenderValues(0xc000014240)`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:378 +0x48`
`main.createGUI(0xc000012110, 0xc000014240, 0xc0, 0x78da04, 0x12)`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:407 +0xbc`
`created by main.main`
`	C:/Users/L/go/src/Voronoi_Image_Manipulation/controls.go:436 +0x11f`
`rax     0x0`
`rbx     0xc00008d9a8`
`rcx     0x8b31`
`rdi     0xc00008d9a8`
`rsi     0x90bc00`
`rbp     0x15ffcf0`
`rsp     0x15ffcc8`
`r8      0xc00003a000`
`r9      0x0`
`r10     0xc0000c0000`
`r11     0x20`
`r12     0x2030000`
`r13     0x0`
`r14     0x20`
`r15     0xc`
`rip     0x0`
`rflags  0x10202`
`cs      0x33`
`fs      0x53`
`gs      0x2b`
`could not remove c:\Users\L\go\src\Voronoi_Image_Manipulation\__debug_bin: remove c:\Users\L\go\src\Voronoi_Image_Manipulation\__debug_bin: Access is denied.`
`Process exiting with code: 0`

tks
Lawrence

**Comment by MauriceGit** [comment]
Hi Lawrence,

Good news, I think I know the issue here (hopefully). 
A few days ago, I was porting https://github.com/MauriceGit/mtOpenGL to Go-Modules for another project I am currently working on. While doing this I upped the used OpenGL Core version to 4.1.

This Voronoi project does not yet use modules and therefore just uses the master branch from mtOpenGL but internally uses OpenGL 3.3 core.

I had issues before with conflicting OpenGL core versions from different imports.
Until I fix this issue in this project (porting to Modules and define which release tag to use from mtOpenGL), you can go to src/github.com/MauriceGit/mtOpenGL and pull the tag 'v1.3.3'.

Alternatively, you could just open the src/github.com/MauriceGit/mtOpenGL/mtOpenGL.go file and change: 
"github.com/go-gl/gl/v4.1-core/gl"
to:
"github.com/go-gl/gl/v3.3-core/gl"

Please report back, if that helps!

Best regards,
Maurice

**Comment by lawrenceong001** [comment]
hey maurice,

thanks for the suggestion -- that seems to do the trick. I'm now able to open up the app and view the apple page! 

funnily enough, I saw somewhere in the debug that it was calling the 4.1 OpenGL and was wondering why that was so since your note said it required 3.3. 

tks again for your help,
Lawrence

**Comment by MauriceGit** [comment]
No worries, my fault :) I'll fix it within the next couple of days!
